---

- name: Install PostgreSQL
  apt:
    name: postgresql
    state: latest

- name: Install PostgreSQL-contrib
  apt:
    name: postgresql-contrib
    state: latest

- name: Install Python-psycopg2
  apt:
    name: python-psycopg2
    state: latest

- name: Add Drupal database
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_db:
    name: "{{ db_name }}"
    encoding: UTF-8

- name: Add Drupal user to database and grant privileges
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_passwd }}"
    priv: "ALL"
    expires: infinity

- name: Copy postgresql.conf
  copy:
    src: etc/postgresql/9.6/main/postgresql.conf
    dest: /etc/postgresql/9.6/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: 0644

- name: Copy pg_hba.conf
  copy:
    src: etc/postgresql/9.6/main/pg_hba.conf
    dest: /etc/postgresql/9.6/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0640
  notify:
    - Restart PostgreSQL
