---
- name: Install Apache2 and other services
  apt:
    name: "{{ apache2,libapache2-mod-php7.0,php7.0,php7.0-pgsql,php7.0-xml,php7.0-mbstring,php7.0-gd,postgresql-client }}"
    state: latest

- name: Create a new virtual host
  copy:
    src: etc/apache2/sites-available/drupal.conf
    dest: /etc/apache2/sites-available/drupal.conf 
    owner: root
    group: root
    mode: 0644

- name: Enable virtual host
  file:
    src: etc/apache2/sites-available/drupal.conf
    dest: /etc/apache2/sites-enabled/drupal.conf
    owner: root
    group: root
    state: link

- name: Delete default virtual host
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify:
    - Restart Apache2
